feat: support for vc+sd-jwt
italia/eudi-wallet-it-python pull request #273
Opened 2024-09-19 07:13 UTC by Zicchio

This pull request closes #269 and #255.
Proposals and modifications are *very* welcomed.

The followings steps where done:
1. define a new interface for general purpose VP token (which is not intended to be a definitive and final iteration; open for review if/when we handle mdoc-cbor tokens); previous iteration "kinda" assume that the only possible VP tokens were vp-envolpes.
2. new interface is intended to be decoupled from trust-layer and direct post processing as much possible for extensibility purposes.
3. define an implementation for that interface for vc+sd-jwt tokens - **In this PR only PIDs are obtained this way**.
4. integrate the usage of the new interface in the `response_handler.py`, with some care regarding extensibility and possible modifications at the trust layers

The final iteration resulted in more modifcations that intended - special care should be taken before pulling in @peppelinux .

Note that in the process we "lost" VP-envolpe; which was expclicity *against* the intent of this pull request. This is because the envolpe hypotesys was spread around in multiple methods and I found it hard to salvage (I don't deny that it might be a skill issue). Hopelly, the new interface should promote a new implementation in short time.

2024-09-19 08:42 UTC, peppelinux commented on pyeudiw/openid4vp/vp_sd_jwt_kb.py
> +
```suggestion
```

2024-09-19 08:46 UTC, peppelinux commented on pyeudiw/openid4vp/vp_sd_jwt_kb.py
> +    _DEFAULT_DISCLOSABLE_CLAIMS = (
please move this in the settings

2024-09-19 09:58 UTC, peppelinux requested changes
Good achievements, anyway we have decided to continue in this PR these two core components:

- trust layer abstraction, according to: https://github.com/italia/eudi-wallet-it-python/issues/267
- credential format abstraction, following the comments within this PR

2024-09-19 09:58 UTC, peppelinux commented on pyeudiw/openid4vp/vp_sd_jwt_kb.py
> +    verifier = JWSHelper(issuer_key)
please protect it with a specialized try/except

2024-09-19 09:58 UTC, peppelinux commented on pyeudiw/satosa/default/response_handler.py
> +    def _detect_typ_iss_vptoken(self, vp_token: str) -> tuple[str, str]:
here we should pass the presentation_submission to guide the _detect_typ_iss_vptoken in using the right class for decoding header/payload

2024-09-25 09:13 UTC, Zicchio commented
dev note: I rebased the branch based on the changes of PR #270 and PR #272 and handles some conflicts (mostly in the ingration test hanges with PR #272).
no further changes are introduced

2024-10-03 08:25 UTC, peppelinux commented on pyeudiw/openid4vp/interface.py
> +        raise NotImplementedError
```suggestion
        raise NotImplementedError

    # TODO: VP proof of possession verification method should be implemented
```

2024-10-03 08:28 UTC, peppelinux commented on pyeudiw/openid4vp/vp_sd_jwt_vc.py
> +        return False
```suggestion
        # TODO: implement revocation check
        return False
```

2024-10-03 08:31 UTC, peppelinux commented on pyeudiw/satosa/default/response_handler.py
> +            raise BadRequestError(f"HTTP method [{http_method}] not supported")
```suggestion
        # TODO: post is required for IT-Wallet, if not post get must work anyway
        # if (http_method := context.request_method.lower()) != ResponseHandler._SUPPORTED_RESPONSE_METHOD:
        #    raise BadRequestError(f"HTTP method [{http_method}] not supported")
```

2024-10-03 08:46 UTC, peppelinux commented on pyeudiw/satosa/default/response_handler.py
> +            # verify vp token and extract user information
```suggestion
            # verify vp token and extract user information
            # TODO: specialized try/except for each call, from line 182 to line 187
```

2024-10-03 08:54 UTC, peppelinux commented on pyeudiw/tests/sd_jwt/test_sdjwt.py
> +        "ZXNzIjogIjEyMyBNYWluIFN0IiwgImxvY2FsaXR5IjogIkFueXRvd24iLCAicmVnaW9u" +
```suggestion
    "WyJBSngtMDk1VlBycFR0TjRRTU9xUk9BIiwgImFkZHJlc3MiLCB7InN0cmVldF9hZGRy", \
    "ZXNzIjogIjEyMyBNYWluIFN0IiwgImxvY2FsaXR5IjogIkFueXRvd24iLCAicmVnaW9u", \
```

2024-10-03 08:55 UTC, peppelinux commented on pyeudiw/tests/sd_jwt/test_sdjwt.py
> +        "IjogIkFueXN0YXRlIiwgImNvdW50cnkiOiAiVVMifV0",
```suggestion
        "IjogIkFueXN0YXRlIiwgImNvdW50cnkiOiAiVVMifV0",
```

2024-10-03 08:58 UTC, peppelinux commented on pyeudiw/tests/settings.py
> +        "get_response": "/get-response",
```suggestion
        "get_response": "/get-response"
```

2024-10-03 08:58 UTC, peppelinux commented on pyeudiw/tests/settings.py
> +        "expiration_time": 5,  # minutes
```suggestion
        "expiration_time": 5  # minutes
```

2024-10-03 09:01 UTC, peppelinux commented on pyeudiw/tests/trust/test_dynamic.py
> +            "jsono_key": "json_value"
```suggestion
            "json_key": "json_value"
```

2024-10-03 09:04 UTC, peppelinux commented on pyeudiw/tests/trust/test_dynamic.py
> +                }
please use `__init__.DEFAULT_DIRECT_TRUST_PARAMS`

2024-10-18 09:43 UTC, peppelinux approved these changes

2024-10-18 09:43 UTC, merged