[Feature] Added Mongo Storage and cache
italia/eudi-wallet-it-python pull request #31
Opened 2023-07-24 11:10 UTC by PascalDR

2023-07-24 11:20 UTC, peppelinux requested changes

2023-07-24 11:20 UTC, peppelinux commented on docker-compose.yml
> +  phpmyadmin:
please comment this to leave it at the will of the user having phpadmin or not

2023-07-24 11:20 UTC, peppelinux commented on example/satosa/pyeudiw_backend.yaml
> +      token_exp_delta: 600000
this collides with the new configuration, please use it

2023-07-24 11:20 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        self.qr_settings = config['qr_code_settings']
this has changed in dev branch, please align this accordingly

2023-07-24 11:20 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        self.token_exp_delta = config['jwks']['token_exp_delta']
the same comment as the previous

2023-07-25 09:11 UTC, peppelinux requested changes

2023-07-25 10:05 UTC, PascalDR commented on pyeudiw/storage/mongo_cache.py
> +            self.db = getattr(self.client, self.storage_conf["db_name"])
Resolved in commit bbcd929b20eea5034251a65fbbcb7fd5f75d18a4

2023-07-25 10:55 UTC, peppelinux approved these changes

2023-07-25 11:10 UTC, merged