#299-feature/presentation submission dynamic handler
italia/eudi-wallet-it-python pull request #314
Opened 2024-11-22 16:30 UTC by LadyCodesItBetter

This PR introduces enhancements to the PresentationSubmission class to improve error handling and dynamic handler initialization based on descriptor_map.

Key points:
 - handlers are dynamically created for each descriptor_map entry based on the format key.
 - handlers attribute contains a dictionary where the key is the index of the descriptor, and the value is the respective handler instance.

2024-11-22 17:38 UTC, peppelinux commented on pyeudiw/openid4vp/presentation_submission/__init__.py
> +
please put some limits on the presentation submission size, in a way that an attacker might not push 10mb of presentation submission causing resource exaustion to the RP

2024-11-25 10:13 UTC, LadyCodesItBetter commented on pyeudiw/openid4vp/presentation_submission/__init__.py
> +class PresentationSubmission:
Done

2024-11-26 12:36 UTC, LadyCodesItBetter commented on pyeudiw/openid4vp/presentation_submission/__init__.py
> +
I've added control for byte size and credential number too

2024-11-26 13:36 UTC, LadyCodesItBetter commented on pyeudiw/openid4vp/presentation_submission/config.yml
> +MAX_SUBMISSION_SIZE: 10 * 1024 * 1024
```suggestion
MAX_SUBMISSION_SIZE: 4096 * 100
```

2024-11-26 13:37 UTC, LadyCodesItBetter commented on pyeudiw/openid4vp/presentation_submission/config.yml
> +MAX_SUBMISSION_SIZE: 4096 * 100
```suggestion
MAX_SUBMISSION_SIZE: 4096
```

2025-01-16 12:55 UTC, Zicchio commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +from typing import Dict, Any
Importing `Dict` is deprecated since Python 3.9 and this project officially supports Python 3.10+ only - use `dict` instead (no import required).
https://docs.python.org/3/library/typing.html#aliases-to-built-in-types

2025-01-16 13:14 UTC, Zicchio commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +        config_path = os.path.join(os.path.dirname(__file__), "config.yml")
What's the point of having a class configurable by editing an obscure configuration file in the *installed* class project that is available who-knows-where based on what `pip` (or other build tool) is used?

@peppelinux @LadyCodesItBetter I'm not sure here what is the intended design goal.

2025-01-16 13:18 UTC, Zicchio commented
>handlers attribute contains a dictionary where the key is the index of the descriptor, and the value is the respective handler instance.

Sorry if the question is dull, but... what is an handler?
Let's say I create an instance of `PresentationSubmission`. How and when am I supposed to use `self.handler`? What should they do?

2025-01-16 13:44 UTC, Zicchio commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +                handlers[index] = cls()  # Instantiate the class
AFAIK the fact that each handler is a class initialized with an empty constructor implies that handlers are functionally just namespace for static methods. It's impossible to known what they should do without doing introspection on what aforementioned namespace contains.

2025-01-16 14:03 UTC, Zicchio commented on pyeudiw/tests/openid4vp/presentation_submission.py
> +import pytest
maybe I'm wrong but if a test class name does not start with `test_` or ends with `_test.py` then `pytest` will not execute them for unit tests (altough ci-cd pipeline might hange this behaviour - I'm not 100% sure how unit tests are configured here).
https://docs.pytest.org/en/stable/explanation/goodpractices.html#test-discovery

2025-01-16 14:11 UTC, Zicchio commented on pyeudiw/openid4vp/presentation_submission/schemas.py
> +    descriptor_map: List[DescriptorSchema]
`List` is also deprecated: use `list` instead

2025-01-16 16:01 UTC, peppelinux commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +        config_path = os.path.join(os.path.dirname(__file__), "config.yml")
the intended propose is for a generic python package, not necessarly used in the iam proxy context

2025-01-16 16:03 UTC, peppelinux commented on pyeudiw/tests/openid4vp/presentation_submission.py
> +import pytest
I can confirm that _test doesn't get loaded

2025-01-16 16:09 UTC, Zicchio commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +        config_path = os.path.join(os.path.dirname(__file__), "config.yml")
The point still stands. Assume I am using the project as a package, that is, I am using it with `pip install pyeudiw` as a part of my project.
To change the configuration of this class, I have to go in the location where pip placed `config.yaml` (which is usually inside the `site-packages`) and and edit it. This is IMO very convoluted and only doable by technically advanced users.

2025-01-22 10:05 UTC, peppelinux commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +        config_path = os.path.join(os.path.dirname(__file__), "config.yml")
yeah, absolutely. We cannot rely on the relative path of tha file distributed within a python package.

2025-01-23 10:50 UTC, LadyCodesItBetter commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +        config_path = os.path.join(os.path.dirname(__file__), "config.yml")
To address the issue of accessibility and management of the `config.yml` file, I propose two possible solutions to enhance flexibility and simplify the use of the library:
- dynamic configurations via env of configuration file (a mechanism to dynamically specify the configuration file path using an environment variable, such as `PYEUDIW_CONFIG_PATH`)
- inline configuration support (allow configuration to be passed directly as a Python dictionary or JSON object during class initialization)

@peppelinux which do you think would work better for our use case?

2025-01-23 11:05 UTC, LadyCodesItBetter commented on pyeudiw/openid4vp/presentation_submission/presentation_submission.py
> +                handlers[index] = cls()  # Instantiate the class
The PresentationSubmission class processes and validates presentation submissions. Its handlers attribute is a dictionary mapping indices from the descriptor_map in the submission to dynamically instantiated handler objects. These handlers are responsible for specific operations (e.g., validation or transformation) tied to the format defined in a configuration file (config.yml).

The handlers are not just namespaces for static methods. They are instances of dynamically loaded classes based on the descriptor formats, designed to process, validate, or manage specific data. Each handler can implement complex logic and maintain state, depending on the requirements of the associated format. This approach ensures modularity, configurability, and extensibility, far beyond the role of a simple placeholder.

2025-01-30 15:16 UTC, peppelinux commented
@LadyCodesItBetter during the dev call we have decided to include wiuthin this PR the interface with the mandatory set of methods to be implemented by the classes used for the VP parse

we also have discussed about the value to handle a proper generalization of each parser configuration, using *args and **kwargs, and therefore enabling the presence of the parameter `config` with each handler configuration

2025-01-30 15:16 UTC, peppelinux requested changes
class interance and configuration generalization are required

2025-02-03 11:55 UTC, LadyCodesItBetter commented
> class interance and configuration generalization are required

@peppelinux should be done

2025-03-18 10:32 UTC, peppelinux commented on pyeudiw/tests/openid4vp/test_presentation_submission.py
> +    ]
there paths doesn't really work

````
{
  "id": "Presentation example 2",
  "definition_id": "Example with multiple VPs",
  "descriptor_map": [
    {
      "id": "ID Card with constraints",
      "format": "ldp_vp",
      "path": "$[0]",
      "path_nested": {
        "format": "ldp_vc",
        "path": "$.verifiableCredential[0]"
      }
    },
    {
      "id": "Example credential disclosing only address",
      "format": "dc+sd-jwt",
      "path": "$[1]"
    }
  ]
}
````

2025-03-18 10:36 UTC, peppelinux commented on pyeudiw/openid4vp/presentation_submission/config.yml
> +    class: "VcSdJwt"
https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/sd_jwt/verifier.py

```suggestion
    module: "pyeudiw.sd_jwt.verifier"
    class: "SDJWTVerifier"
```

2025-03-18 15:50 UTC, closed without merging