Initial support to sd-jwt
italia/eudi-wallet-it-python pull request #34
Opened 2023-07-26 09:48 UTC by PascalDR

2023-07-26 19:56 UTC, peppelinux requested changes

2023-07-26 20:20 UTC, peppelinux requested changes

2023-07-26 20:20 UTC, peppelinux commented on pyeudiw/tests/tools/specifications.yml
> +    - !sd "US"
this doesn't make any sense, please use the attributes defined in the italian specs, pid-data-model.rst

2023-07-26 20:20 UTC, peppelinux commented on pyeudiw/tests/tools/test_sd_jwt.py
> +        {"issuer": "http://test.com", "default_exp": 60, "specification_file": "./pyeudiw/tests/tools/specifications.yml", "no_randomness": True},
please do not open a specification file on each call but load the specification in a constructor and use it runtime without any filesystem read access

2023-07-26 20:20 UTC, peppelinux commented on pyeudiw/tests/tools/test_sd_jwt.py
> +    user_claims_path = "./pyeudiw/tests/tools/specifications.yml"
see my previous comment

2023-07-26 20:20 UTC, peppelinux commented on pyeudiw/tests/tools/test_sd_jwt.py
> +        {"issuer": "http://test.com", "default_exp": 60, "specification_file": "./pyeudiw/tests/tools/specifications.yml", "no_randomness": True},
see my previous comment

2023-07-26 20:20 UTC, peppelinux commented on pyeudiw/tests/tools/test_sd_jwt.py
> +    testcase = load_yaml_specification("./pyeudiw/tests/tools/specifications.yml")
see my previous comment

2023-07-26 20:20 UTC, peppelinux commented on pyeudiw/tests/tools/test_sd_jwt.py
> +            "specification_file": "./pyeudiw/tests/tools/specifications.yml",
see my previous comment

2023-07-28 09:30 UTC, PascalDR commented on pyeudiw/satosa/backend.py
> +        # res_url = f'{self.config["authorization"]["url_scheme"]}://authorize?{url_params}' ?
Resolved in commit [f4d77b6](https://github.com/italia/eudi-wallet-it-python/pull/34/commits/f4d77b6b4a46559f48fb8e1cc9214395f24ed43c)

2023-07-28 09:35 UTC, peppelinux commented on pyeudiw/tests/satosa/test_backend.py
> +        "specification_file": "./pyeudiw/tests/tools/specifications.yml",
please take the specification def from the backend config and not from the filesystem

2023-07-28 09:36 UTC, peppelinux commented on pyeudiw/tests/satosa/test_backend.py
> +    "sd_jwt_settings": {
please remove `_settings`, just `sd_jwt`

2023-07-28 09:39 UTC, peppelinux requested changes

2023-07-28 09:39 UTC, peppelinux commented on pyeudiw/tests/satosa/test_backend.py
> +        user_claims_path = "./pyeudiw/tests/tools/specifications.yml"
please take the specification def from a string and not from the filesystem

2023-07-28 09:39 UTC, peppelinux commented on pyeudiw/tests/satosa/test_backend.py
> +            "state": "3be39b69-6ac1-41aa-921b-3e6c07ddcb03",
add the nonce

and add a verification of the nonce in the backend

2023-07-28 09:39 UTC, peppelinux commented on pyeudiw/tests/tools/test_sd_jwt.py
> +    user_claims_path = "./pyeudiw/tests/tools/specifications.yml"
please take the specification def from a string and not from the filesystem

2023-07-28 13:17 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +    def _check_vp_token(self, vp_token: str) -> dict:
here we have -> while then a tuple is returned

2023-07-28 13:19 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        issuer_jwk = JWK(self.config["federation"]["federation_jwks"][1])
[0] instead

2023-07-28 13:20 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        jwk = JWK(self.config["federation"]["federation_jwks"][0], "RSA")
I do not love anonymous params, I'll change it to

`alg = "RSA"`

2023-07-28 13:21 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        nonce = decrypted_data.get("nonce", None) #TODO Fix this field handling
the nonce is just in the vp token and not in the redirect response, I'll remove it

2023-07-28 13:21 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        if type(vp_token) is str:
I'd prefer

`if isinstance(vp_token, str)`

2023-07-28 13:22 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +            valid, value = self._check_vp_token(vp_token)
check_vp_token should be in `pyeudiw.openid4vp` module, and used in the satosa backend

2023-07-28 13:23 UTC, peppelinux commented on pyeudiw/sd_jwt/__init__.py
> +        "exp": iat_now() + (settings["default_exp"] * 60)  # in seconds
please add a function in the tools to get the default_exp instead of using * 60 everytime  in the code

2023-07-28 13:24 UTC, peppelinux approved these changes

2023-07-28 16:11 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +        jwk = JWK(self.config["federation"]["federation_jwks"][0], "RSA")
```suggestion
        jwk = JWK(self.config["federation"]["federation_jwks"][0], key_type="RSA")
```

2023-07-28 16:15 UTC, peppelinux requested changes

2023-07-28 16:15 UTC, peppelinux commented on pyeudiw/sd_jwt/__init__.py
> +    def cb_get_issuer_key(issuer: str):
Please don't nest function in other function

this can be done just for decorators, and this is not the case

2023-07-28 16:15 UTC, peppelinux commented on pyeudiw/satosa/backend.py
> +                else:
please don't do hadoken code

we just can remove the `else` and use `elif not nonce` ...

2023-07-28 18:30 UTC, peppelinux approved these changes

2023-07-28 18:31 UTC, merged