Satosa disco login
italia/eudi-wallet-it-python pull request #78
Opened 2023-08-03 11:11 UTC by MurruAlessio

the following changes resolve the following issue : https://github.com/italia/eudi-wallet-it-python/issues/57

and make the graphical changes to the discovery page: https://github.com/orgs/italia/projects/19/views/1?pane=issue&itemId=34479233

2023-08-03 17:30 UTC, MurruAlessio commented
Still in progress to resolve a Cors policy issue when downloading font files

2023-08-04 09:10 UTC, MurruAlessio commented
The problem was solved by adding the --check-static ./static/ option to the uwsgi command to start the IAM Proxy server on localhost:10000. This allowed the server to properly serve the static resources in the ./static directory.

2023-08-04 10:43 UTC, peppelinux requested changes

2023-08-04 10:43 UTC, peppelinux commented on example/satosa/static/idem/img/IDEM_logo_mono_blu.svg
Please use the white monocrome logo given by GARR

2023-08-04 10:47 UTC, merged